### ISSUE TITLE
translation - create function that recived lyrics and target lang, translate with chatgpt

### ISSUE THREAD

**Issue by yishain11** [Makes-Innovation-Hub/harmony#15]
DOD:

- [x] create a function that takes a lyrics and target lang, original lang song name and artist
- [x] create endpoint for this function
- [x] search lyrics in mongo db in songs collection - if there are lyrics for this lang - send back to user
- [x] if no stored lyrics  -translate the lyrics using chatgpt open ai api - create prompt asking to translate lyrics X into lang Y
- [x] store new lyrics in mongo in the right place
- [x] send to user

**Comment by ArturLabenskyy** [comment]
Ok, the translation function is working. BUT: it does some issues when i trying to save translated lyrics, so i commented some code in SongSchema to check if function working correctly. It's gonna take more time to fix problems with data saving in mongoDB
